# Generated by Django 3.1.14 on 2023-01-30 16:01

import autoslug.fields
import cœur.models
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=100, null=True)),
                ('status', models.BooleanField(default='False')),
            ],
            options={
                'verbose_name_plural': 'Adresse',
            },
        ),
        migrations.CreateModel(
            name='CartOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, default='1.99', max_digits=12)),
                ('suivi_paiement', models.BooleanField(default='False')),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('statut_produit', models.CharField(choices=[('traitement', 'Traitement'), ('expédié', 'Expédié'), ('livré', 'Livré')], default='traitement', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Mon Panier ',
            },
        ),
        migrations.CreateModel(
            name='CartOrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numéro_facture', models.CharField(max_length=200)),
                ('statut_produit', models.CharField(max_length=200)),
                ('article', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('quantité', models.IntegerField(default=0)),
                ('prix', models.DecimalField(decimal_places=2, default='1.99', max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default='1.99', max_digits=12)),
            ],
            options={
                'verbose_name_plural': 'Articles de Mon Panier ',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='cat', unique=True)),
                ('titre', models.CharField(default='model', max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=200, null=True, populate_from='titre', unique=True)),
                ('image', models.ImageField(default='', upload_to='category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='cel', unique=True)),
                ('titre', models.CharField(default='model', max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=200, null=True, populate_from='titre', unique=True)),
                ('image', models.ImageField(default='collection.jpg', upload_to='collection')),
            ],
            options={
                'verbose_name_plural': 'Collections',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='', upload_to='product-images')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Images Produits',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avis', models.TextField()),
                ('note', models.IntegerField(choices=[(1, '✨☆☆☆☆'), (2, '✨✨☆☆☆'), (3, '✨✨✨☆☆'), (4, '✨✨✨✨☆'), (5, '✨✨✨✨✨')], default=None)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': "Évaluations d'utilisateurs",
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='prd', unique=True)),
                ('titre', models.CharField(default='t-shirt', max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=200, null=True, populate_from='titre', unique=True)),
                ('image', models.ImageField(default='', upload_to=cœur.models.user_directory_path)),
                ('image_view', models.ImageField(default='', upload_to=cœur.models.user_directory_path)),
                ('description', models.TextField(blank=True, default="c'est un produit", null=True)),
                ('prix', models.DecimalField(decimal_places=2, default='1.99', max_digits=12)),
                ('prix_ancien', models.DecimalField(decimal_places=2, default='2.99', max_digits=12)),
                ('specificationns', models.TextField(blank=True, null=True)),
                ('statut_produit', models.CharField(choices=[('en_attente', 'En Attente'), ('en_cours', 'En Cours'), ('publier', 'Publier'), ('rejeté', 'Rejeté'), ('désactivé', 'Désactivé')], default='en_cours', max_length=100)),
                ('status', models.BooleanField(default='True')),
                ('en_stock', models.BooleanField(default='True')),
                ('featured', models.BooleanField(default='False')),
                ('digital', models.BooleanField(default='False')),
                ('ref', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=4, max_length=10, prefix='ref', unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Produits',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='vid', unique=True)),
                ('titre', models.CharField(default='Paul', max_length=100)),
                ('image', models.ImageField(default='', upload_to=cœur.models.user_directory_path)),
                ('description', models.TextField(blank=True, default='je suis un fournisseur', null=True)),
                ('adresse', models.CharField(default='1 Rue du fournisseur ', max_length=100)),
                ('contact', models.CharField(default='+33 7 64 45 02 23 ', max_length=100)),
                ('temps_chat', models.CharField(default='100', max_length=100)),
                ('durée_de_livraison', models.CharField(default='100', max_length=100)),
                ('évaluation_authentiques', models.CharField(default='100', max_length=100)),
                ('retour_sous_30_jours', models.CharField(default='100', max_length=100)),
                ('période_de_garantie', models.CharField(default='100', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Fournisseurs',
            },
        ),
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cœur.produit')),
            ],
            options={
                'verbose_name_plural': "Ma liste d'envies",
            },
        ),
    ]
