# Generated by Django 3.1.14 on 2023-01-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cœur', '0002_auto_20230130_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='produit',
            name='slug',
            field=models.SlugField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
