# Generated by Django 3.1.14 on 2023-01-30 16:29

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cœur', '0003_auto_20230130_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='titre', unique=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='titre', unique=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='titre', unique=True),
        ),
    ]
