# Generated by Django 3.1.14 on 2023-01-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cœur', '0005_auto_20230131_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='en_stock',
            field=models.BooleanField(choices=[('en_stock', 'En Stock'), ('rupture', 'Rupture')], default='True'),
        ),
    ]
