# Generated by Django 3.1.14 on 2023-01-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cœur', '0007_auto_20230131_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='en_stock',
            field=models.BooleanField(default='True'),
        ),
    ]
