# Generated by Django 3.1.14 on 2023-02-01 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cœur', '0008_auto_20230131_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='cœur.category'),
        ),
    ]
