# Generated by Django 3.1.14 on 2023-02-01 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cœur', '0009_auto_20230201_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cœur.category'),
        ),
    ]
