# Generated by Django 3.1.14 on 2023-02-01 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cœur', '0010_auto_20230201_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='collection',
            new_name='collections',
        ),
    ]
