# Generated by Django 3.1.14 on 2023-02-01 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cœur', '0011_auto_20230201_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='collections',
            new_name='collection',
        ),
    ]
