# Generated by Django 3.1.14 on 2023-02-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cœur', '0012_auto_20230201_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='megamenu_image',
            field=models.ImageField(default='collection.jpg', upload_to='collection'),
        ),
    ]
