# Generated by Django 3.1.14 on 2023-02-01 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cœur', '0013_collection_megamenu_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='megamenu_image',
        ),
    ]
