# Generated by Django 3.1.14 on 2023-02-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cœur', '0014_remove_collection_megamenu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(default='', upload_to='produits'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image_view',
            field=models.ImageField(default='', upload_to='produits'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='image',
            field=models.ImageField(default='', upload_to='fournisseurs'),
        ),
    ]
