# Generated by Django 3.1.14 on 2023-02-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cœur', '0016_auto_20230201_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image_sm_1',
            field=models.ImageField(default='', help_text='Taille: 1488 x 1488', upload_to='produit-single1/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='produit',
            name='image_sm_2',
            field=models.ImageField(default='', help_text='Taille: 1488 x 1488', upload_to='produit-single2/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='produit',
            name='image_sm_3',
            field=models.ImageField(default='', help_text='Taille: 1488 x 1488', upload_to='produit-single3/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='', help_text='Taille: 1024 x 1024', upload_to='category'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(default='collection.jpg', help_text='Taille: 1024 x 1024', upload_to='collection'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(default='', help_text='Taille: 1024 x 1024', upload_to='produits/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image_view',
            field=models.ImageField(default='', help_text='Taille: 1024 x 1024', upload_to='produits/%Y/%m/%d'),
        ),
    ]
