# Generated by Django 3.1.14 on 2023-02-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cœur', '0017_auto_20230201_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image_sm_1',
            field=models.ImageField(default='', help_text='Taille: 1488 x 1488', upload_to='media/produit-single1/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image_sm_2',
            field=models.ImageField(default='', help_text='Taille: 1488 x 1488', upload_to='media/produit-single2/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image_sm_3',
            field=models.ImageField(default='', help_text='Taille: 1488 x 1488', upload_to='medial/produit-single3/%Y/%m/%d'),
        ),
    ]
