# Generated by Django 3.1.14 on 2023-02-02 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cœur', '0019_auto_20230201_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='prix',
            new_name='price',
        ),
    ]
