# Generated by Django 3.1.14 on 2023-02-02 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cœur', '0020_auto_20230202_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='prix',
            new_name='price',
        ),
    ]
