# Generated by Django 3.1.14 on 2023-02-02 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cœur', '0022_auto_20230202_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='coid',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='vid',
        ),
    ]
