# Generated by Django 3.1.14 on 2023-02-03 12:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cœur', '0023_auto_20230202_1442'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produit',
            new_name='Product',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='cœur_produi_id_e724c9_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='cœur_produi_titre_6956d2_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='cœur_produi_date_3550f7_idx',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id', 'slug'], name='cœur_produc_id_4667df_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['titre'], name='cœur_produc_titre_376d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-date'], name='cœur_produc_date_efba5a_idx'),
        ),
    ]
