# Generated by Django 3.1.14 on 2023-02-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20230203_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('commande_créée', 'Commande Créée'), ('en_attente', 'En Attente'), ('en_cours_de_traitement', 'En Cours De Traitement'), ('Commande_expédiée', 'Commande Expédiée'), ('Commande_livrée', 'Commande Livrée'), ('Completed', 'Completed')], default='commande_créée', max_length=30),
        ),
    ]
